name: Juliano Padilha
description: ''
meta_descritipn: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: /
domain_name: 'julianopadilha.com'
google_analytics: 'UA-78425258-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'julianopadilha.com'
author:         'Juliano Padilha'
